<template>
    <div>
        <h5 class="text-center">Producto</h5>
        <hr>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Código</label>
            <span class=" col-sm-7">Código</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Código Alterno</label>
            <span class=" col-sm-7">Código</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Nombre</label>
            <span class=" col-sm-7">Nombre</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Stock</label>
            <span class=" col-sm-7">10 unidades de medida</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">IVA</label>
            <span class=" col-sm-7">Tiene IVA</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Ganancia Minorista</label>
            <span class=" col-sm-4">$0,30</span>
            <span class=" col-sm-3">(20%)</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Ganancia Mayorista</label>
            <span class=" col-sm-4">$0,30</span>
            <span class=" col-sm-3">(20%)</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Ganancia Proveedor</label>
            <span class=" col-sm-4">$0,30</span>
            <span class=" col-sm-3">(20%)</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Ganancia Distribuidor</label>
            <span class=" col-sm-4">$0,30</span>
            <span class=" col-sm-3">(20%)</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Ganancia Cliente Fiel</label>
            <span class=" col-sm-4">$0,30</span>
            <span class=" col-sm-3">(20%)</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Descuento</label>
            <span class=" col-sm-7">10% (Descuendo especial)</span>
        </div>
        <hr>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Grupo</label>
            <span class=" col-sm-7">Grupo</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Marca</label>
            <span class=" col-sm-7">Marca</span>
        </div>
        <div class="form-group row">
            <label for="disscount_special" class="col-sm-5">Linea</label>
            <span class=" col-sm-7">Linea</span>
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            
        }
    },
}
</script>